### ISSUE TITLE
La aprobación requiere varios pasos

### ISSUE THREAD

**Issue by restrepo** [Equipo-de-desarrollo-IF-UDEA/siga#170]
En la cuenta DIRECCIONFISICA se encuentra la solicitud [3127](https://siga-fcen.com/solicitudes/ver/3127/comision)

Cuando se dió click sobre el botón "Aprobar" por primera vez, la solicitud se quedó en estado  "SOLICITADA"

He tenido que dar un segundo click en "Aprobar" para que pasará a estado "VISTO BUENO" 

En el historial de estado aparecen los tres eventos. Si la aplicación hubiese funcionado correctamente sólo debería haber 2:

Historial de estados:
```
Estado	Fecha de Actualización	Observación
VISTO BUENO	martes, 18 de abril de 2023	por Director del instituto
SOLICITADA	martes, 18 de abril de 2023	Solicitud creada
VISTO BUENO	martes, 18 de abril de 2023	por Director del instituto
```

**Comment by alwos19** [comment]
Se le está haciendo seguimiento a la tabla intermedia entre solicitud y estado, donde quedan todos los registros, estos conflictos se están dando a causa de la migración que se importó desde comisiones V2.

**Comment by alwos19** [comment]
Fue resulto el inconveniente
