### ISSUE TITLE
Rechazo genera error de aprobación

### ISSUE THREAD

**Issue by restrepo** [Equipo-de-desarrollo-IF-UDEA/siga#175]
La solicitud

https://siga-fcen.com/solicitudes/ver/3175/comision

de la cuenta DIRECCIONFISICA que tiene el historial de estados:

SOLICITADA (creada) → RECHAZADA → SOLICITADA (Actualizada)

Cuando se intenta Aprobar con el botón correspondiente: genera "ERROR DEL SERVIDOR"

**Comment by alwos19** [comment]
Se hizo una nueva migración, donde se resolvió el error
